Added custom train, test and valid data-path functionality
EleutherAI/gpt-neox pull request #305
Opened 2021-05-07 13:21 UTC by preethamgali

Added new feature https://github.com/EleutherAI/gpt-neox/issues/263

2021-05-07 14:19 UTC, ShivanshuPurohit approved these changes

2021-05-07 15:03 UTC, sdtblck requested changes

2021-05-07 16:44 UTC, preethamgali commented on megatron/training.py
> +                                               for name in ["train", "valid", "test"]]
Yes that's true, I will modify it tomorrow.

2021-05-08 04:58 UTC, preethamgali commented on megatron/training.py
> +                                               for name in ["train", "valid", "test"]]
I have fixed it please check it.

2021-05-08 22:19 UTC, sdtblck approved these changes

2021-05-08 22:19 UTC, merged